name: Deploy to Server

on:
  push:
    branches:
      - master    # 注意是main分支还是master分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"  # 注意你项目的node版本

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          # 关键验证步骤
          echo "构建输出验证："
          ls -la .vitepress/dist || echo "默认输出目录不存在"
          ls -la ../dist || echo "自定义输出目录不存在"
          [ -d ".vitepress/dist" ] && find .vitepress/dist -type f | head -5
          [ -d "../dist" ] && find ../dist -type f | head -5

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.5
        # see https://github.com/appleboy/scp-action/tree/v0.1.5/
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: ".vitepress/dist"
          target: "/home/dist"
